# Generated by Django 4.2.26 on 2025-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
